# 参考1: https://blog.mafeifan.com/DevOps/GithubActions/Docker%E6%9E%84%E5%BB%BA%E9%95%9C%E5%83%8F%E5%92%8C%E6%8E%A8%E9%80%81%E5%88%B0docker-hub.html
# 参考2: https://docs.docker.com/ci-cd/github-actions/

name: CI to Docker Hub 

on:
  workflow_dispatch:
  push:
        branches: [ master ]
   # tags:
   #   - "v*.*.*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: finleyma/simplewhale:latest
          build-args: |
            arg1=value1
            arg2=value2
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
